### ISSUE TITLE
希望能修改ApkMetaTranslator这个类让ApkMeta可以直接获取manifest文件中的“meta-data”信息

### ISSUE THREAD

**Issue by rocrocroc** [clearthesky/apk-parser#56]
如果没时间修改，我可以帮忙贡献代码

**Comment by clearthesky** [comment]
ApkMeta里面是放最常用的那些信息。manifest文件中的元素很多，像meta-data这个标签，可以放在不同的地方，意义也不明确，不适合放在ApkMeta里面。
建议使用getManifestXml来获得manifest的xml表示，然后解析xml来拿到想要的内容。

**Comment by rocrocroc** [comment]
那行吧，但这样我得到meta-data效率不高
